### ISSUE TITLE
olric in k8s is always in the initial member list

### ISSUE THREAD

**Issue by hacktmz** [buraksezer/olric#121]
env: ubuntu 18.04  k8s
describe: When I update the version, there will be a problem of synchronizing nodes all the time.Then it will be killed over time(20minutes). Never wait for this sentence `Join completed`

![image](https://user-images.githubusercontent.com/11882938/131334423-78b90841-3942-47bc-b0fc-b526dd6b82fb.png)
![image](https://user-images.githubusercontent.com/11882938/131334462-358ebb68-7a07-4d14-8d0d-5560e7968065.png)

this is my config
```
olricd:
  bindPort: 3320
  serializer: gob
  keepAlivePeriod: 300s
  requestTimeout: 5s
  partitionCount:  271
  replicaCount: 1
  writeQuorum: 1
  readQuorum: 1
  readRepair: false
  bootstrapTimeout: 1000s
  replicationMode: 0
  memberCountQuorum: 1

storageEngines:
  config:
    kvstore:
      tableSize: 4194304

logging:
  verbosity: 6
  level: DEBUG
  output: stderr

memberlist:
  environment: "lan"
  bindPort: 3322
  enableCompression: false
  joinRetryInterval: "500ms"
  maxJoinAttempts: 100

client:
  dialTimeout: -1s
  readTimeout: 2s
  writeTimeout: 2s
  keepAlive: 15s
  minConn: 1
  maxConn: 100
  poolTimeout: 2s

dmaps:
  img-bucket:
    maxIdleDuration: "3600s"
    ttlDuration: "14400s"
    maxKeys: 15000
    maxInuse: 3000000000 # in bytes ;3GB
    lRUSamples: 10
    evictionPolicy: "LRU" # NONE/LRU

  resp-bucket:
    maxIdleDuration: "36000s"
    ttlDuration: "36000s"
    maxKeys: 150000
    maxInuse: 300000000 # in bytes ;300MB
    lRUSamples: 10
    evictionPolicy: "LRU" # NONE/LRU

serviceDiscovery:
  provider: "k8s"
  path: "/usr/lib/olric-cloud-plugin.so"
  args: 'label_selector="app = img-proxy"'
```
