### ISSUE TITLE
question about olricd log

### ISSUE THREAD

**Issue by ShawnHsiung** [buraksezer/olric#124]
```
logging:
  verbosity: 6
  level: DEBUG
  output: /var/log/olricd.log
```

hi,  currently it's seems not supported output log to a file, all logs go to stdout or stderr, may we have a plan to support output logs to a file?

```
type logging struct {
	Verbosity int32  `yaml:"verbosity"`
	Level     string `yaml:"level"`
	Output    string `yaml:"output"`
}

var logOutput io.Writer
	switch {
	case c.Logging.Output == "stderr":
		logOutput = os.Stderr
	case c.Logging.Output == "stdout":
		logOutput = os.Stdout
	default:
		logOutput = os.Stderr
}
```
