### ISSUE TITLE
NewClusterClient i/o timeout

### ISSUE THREAD

**Issue by darkweak** [buraksezer/olric#264]
Hello, I'm trying to use olric as client-server mode using the NewClusterClient method but it returns an i/o timeout.

Here is the reproducible code
```dockerfile
FROM golang:latest as olric

RUN mkdir -p src/github.com/buraksezer
WORKDIR /go/src/github.com/buraksezer

RUN git clone https://github.com/buraksezer/olric
WORKDIR /go/src/github.com/buraksezer/olric/cmd/olricd
COPY ./olric.yml olricd-local.yaml
COPY ./olric.yml /etc/olricd.yaml

EXPOSE 3320 3322

CMD ["go", "run", "main.go"]
```

```yaml
# compose.yml
services:
  olric:
    build:
      context: .
      target: olric
    restart: on-failure
    ports:
      - 3320:3320
      - 3322:3322
```

Go code:
```go
package main

func main() {
	client, err := olric.NewClusterClient([]string{"127.0.0.1:3320"})
	fmt.Printf("client error = %#v\n", err)
}
```

Output:
```
client error = &fmt.wrapError{msg:"error while loading the routing table: tcp 172.23.0.2:3320: i/o timeout", err:(*errors.errorString)(0x1400011cfd0)}
```
