### ISSUE TITLE
Olric embedded in a Kubernetes StatefulSet throws network errors, rejects writes and uses too much CPU

### ISSUE THREAD

**Issue by cobexer** [buraksezer/olric#54]
The intended use case for Olric in my application is to act as a replicated cache, that doesn't need transactions or disk persistence, but needs to keep values in case of node/datacenter failures and through upgrades.

To achieve this I added olric embedded to my application which is deployed using a [Kubernetes StatefulSet](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/) with 3 replicas.

To discover the other replicas of my application for olric I use the olric-cloud-plugin, and after some guessing and trial and error I got it to discover the other peers and have olric seem to form a cluster.

However with 3 replicas of my application, MinimumReplicaCount = 2 and ReplicationMode = AsyncReplicationMode olric seems to be unhappy:
* writes often fail with network I/O timeouts
* one member uses ~100% of a CPU all the time
* memory use seems very high
* not sure node cleanup works at all (relevant after application updates/node restarts,...)

I still need to try this use case with olricd to see if I can reproduce the problem there.

Now I know that my application (because it is still in it's early stages) has a dumb behavior: the data that needs to be cached comes from the kubernetes API server and all nodes receive the same data, and also all write the same values to the olric DMap.
You documentation leads me to believe this should be fine, because the last write will win.

I guess I'll have to write a sample application to demonstrate the problem... but I don't have access to the applications code right now, so I will add that later.

**Comment by buraksezer** [comment]
Thank you for reporting. The problem is very likely to unrelated with Kubernetes. Because of this I tried to reproduce it in a multi-container Docker environment but it seems to work fine. What version of Olric do you use? I have tried with Olric v0.3.0-beta.1. 

If you can provide some sample code and configuration to reproduce the issue, it would be awesome. Especially Kubernetes configuration is very critical.

**Comment by cobexer** [comment]
Kubernetes StatefulSet:
```yaml
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: test-container-id-to-image-cache
  namespace: playground
  labels:
    app.kubernetes.io/instance: test
    app.kubernetes.io/name: container-id-to-image-cache
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: test
      app.kubernetes.io/name: container-id-to-image-cache
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: test
        app.kubernetes.io/name: container-id-to-image-cache
    spec:
      restartPolicy: Always
      serviceAccountName: test-container-id-to-image-cache
      imagePullSecrets:
        - name: regcred
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
        - name: test-container-id-to-image-cache
          image: myregistry/container-id-to-image-cache:1.0.3-git9949bea
          command:
            - /app/container-id-to-image-cache
          args:
            - '--namespace'
            - playground
            - '--name'
            - container-id-to-image-cache
            - '--instance'
            - test
            - '--loglevel'
            - DEBUG
          resources:
            limits:
              cpu: 1200m
            requests:
              cpu: 100m
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      serviceAccount: test-container-id-to-image-cache
      dnsPolicy: ClusterFirst
  serviceName: test-container-id-to-image-cache
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  revisionHistoryLimit: 10

```

**Comment by cobexer** [comment]
The relevant Go code I hope:
```go
type KVCache struct {
	Log      *zap.SugaredLogger
	LogLevel zapcore.Level
	db       *olric.Olric
	kvmap    *olric.DMap
}

func (kvc *KVCache) Start(namespace, name, instance string) error {
	c := config.New("lan")
	c.MaxJoinAttempts = 3600
	c.JoinRetryInterval = time.Second * 5
	c.ReadRepair = true
	c.ReplicationMode = config.AsyncReplicationMode
	c.BindPort = 4220
	c.MemberlistConfig.BindPort = 3322
	c.MemberlistConfig.AdvertisePort = 3322
	c.MemberlistConfig.DeadNodeReclaimTime = time.Second * 5
	c.LogLevel = kvc.LogLevel.String()
	c.ReplicaCount = 2
	c.Logger = zap.NewStdLog(kvc.Log.Desugar())
	c.KeepAlivePeriod = time.Second * 20
	c.DialTimeout = time.Second * 300
	c.RequestTimeout = time.Second * 30
	c.WriteQuorum = 1
	cd := &discovery.CloudDiscovery{}
	labelSelector := fmt.Sprintf("app.kubernetes.io/name=%s,app.kubernetes.io/instance=%s", name, instance)
	c.ServiceDiscovery = map[string]interface{}{
		"plugin":   cd,
		"provider": "k8s",
		"args":     fmt.Sprintf("namespace=%s label_selector=\"%s\"", namespace, labelSelector),
	}

	// Callback function. It's called when this node is ready to accept connections.
	olricCtx, cancel := context.WithCancel(context.Background())
	c.Started = func() {
		kvc.Log.Info("KVCache: Olric is ready to accept connections")
		cancel()
	}

	var err error
	kvc.db, err = olric.New(c)

	if err != nil {
		return errors.Wrapf(err, "KVCache: Failed to create Olric instance: %v", err)
	}

	go func() {
		// Call Start at background. It's a blocker call.
		err = kvc.db.Start()
	}()

	<-olricCtx.Done() // startup finished

	if err != nil {
		return errors.Wrapf(err, "KVCache: olric.Start returned an error: %v", err)
	}

	kvc.kvmap, err = kvc.db.NewDMap("kvcache")

	if err != nil {
		return errors.Wrapf(err, "KVCache: faield to create DMap: %v", err)
	}

	return nil
}
```

**Comment by cobexer** [comment]
The Kubernetes Headless service used for the peer discovery I think:
```yaml
kind: Service
apiVersion: v1
metadata:
  name: test-container-id-to-image-cache
  namespace: playground
  labels:
    app.kubernetes.io/instance: test
    app.kubernetes.io/name: container-id-to-image-cache
spec:
  ports:
    - name: olric
      protocol: TCP
      port: 4220
      targetPort: 4220
    - name: memberlist
      protocol: TCP
      port: 3322
      targetPort: 3322
  selector:
    app.kubernetes.io/instance: test
    app.kubernetes.io/name: container-id-to-image-cache
  clusterIP: None
  type: ClusterIP
  sessionAffinity: None

```

**Comment by cobexer** [comment]
Please let me know if you need more!

**Comment by buraksezer** [comment]
Thank you @cobexer. I'm going to try to reproduce the problem. The underlying problem can be a redirect loop. I implemented a fix in **v0.3.0-beta.4**. You may want to try with this version.

> writes often fail with network I/O timeouts

This may indicate a problem with Kubernetes networking. Olric nodes can discover each other (via memberlist), but they cannot work together. I saw this problem before. Take a look at my Kubernetes configuration: https://github.com/buraksezer/olric-kubernetes/blob/master/olricd.yaml#L78

```yaml
apiVersion: v1
kind: Service
metadata:
  name: memberlist
spec:
  selector:
    run: olricd
  clusterIP: None
  ports:
  - port: 3322
    protocol: TCP
    targetPort: 3322

---

apiVersion: v1
kind: Service
metadata:
  name: olricd
spec:
  selector:
    run: olricd
  ports:
  - port: 3320
    protocol: TCP
    targetPort: 3320
```

> one member uses ~100% of a CPU all the time
> memory use seems very high

An infinite loop and memory/goroutine leak. This can be triggered by redirect loop problem. We need to find the root cause of the problem.
