### ISSUE TITLE
Continuous delivery to Docker Hub

### ISSUE THREAD

**Issue by bittrance** [buraksezer/olric#88]
It would be good if Olric could continuously release a `latest` Docker image. As it is now, the latest published Docker mages `latest` and `v0.3.0-beta.6` which are incompatible with current master, making it harder than it could be to test Olricd.
```
$ go run cmd/olric-cli/main.go -a 192.168.224.200:3320
Type "help" or "help <command-name>" to learn how to use.
[192.168.224.200:3320] » use testo
use testo
[192.168.224.200:3320] » put foo bar
[192.168.224.200:3320] » get foo
panic: runtime error: slice bounds out of range [:25] with capacity 17

goroutine 1 [running]:
github.com/buraksezer/olric/internal/kvstore.(*Entry).Decode(0xc00020c200, 0xc00022a030, 0x11, 0x11)
	/home/quest/projects/external/olric/internal/kvstore/entry.go:117 +0x205
github.com/buraksezer/olric/client.(*DMap).Get(0xc0000c3d70, 0xc000224064, 0x3, 0xa6ce88, 0x1, 0xc000224064, 0x3)
	/home/quest/projects/external/olric/client/dmap.go:46 +0x185
github.com/buraksezer/olric/cmd/olric-cli/cli.(*CLI).evalGet(0xc000118b00, 0xc0000c3d70, 0xc000208050, 0x1, 0x1, 0x0, 0x966200)
	/home/quest/projects/external/olric/cmd/olric-cli/cli/evaluate.go:86 +0x7a
github.com/buraksezer/olric/cmd/olric-cli/cli.(*CLI).evaluate(0xc000118b00, 0xc0002a6184, 0x5, 0xc000224060, 0x7, 0x7, 0x0)
	/home/quest/projects/external/olric/cmd/olric-cli/cli/evaluate.go:229 +0x6f5
github.com/buraksezer/olric/cmd/olric-cli/cli.(*CLI).WaitForCommand(0xc000118b00, 0xc0002a6184, 0x5, 0x0, 0x0)
	/home/quest/projects/external/olric/cmd/olric-cli/cli/cli.go:211 +0x4b1
main.main()
	/home/quest/projects/external/olric/cmd/olric-cli/main.go:120 +0x990
```
Adding the following (plus a secret) at the end of `.github/workflows/ci.yml` should achieve this (untested):
```
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        push: true
        context: .
        tags: olricio/olricd:latest
```
The reason I have not made a PR with this is that there are many different ways to achieve continuous delivery and it feels presumptuous to dictate Olric's development process when I have no immediate plan to contribute source changes. If you think this is what you want, I'll be happy to reformulate the above suggestion as a PR.
